env:
  node: true
  es6: false
  jest: true
  commonjs: true
extends:
  - google
  - 'plugin:prettier/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2019
  sourceType: script
plugins:
  - prettier
rules: {}
